<!DOCTYPE html>
<html ng-app="tesonetFullstackPartyApp">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Base href is a must for html5 mode links in angular -->
        <base href="/">

        <link rel="stylesheet" href="/static/third_party/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/static/third_party/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="/static/css/main.css" />

        <script src="/static/third_party/angular/angular.min.js"></script>
        <script src="/static/third_party/angular-route/angular-route.min.js"></script>
        <script src="/static/third_party/moment/min/moment.min.js"></script>
        <script src="/static/third_party/ng-time-relative/dist/ng-time-relative.js"></script>
        <script src="/static/js/angular_app/script.js"></script>
    </head>

    <body ng-controller="mainController" ng-view>
    </body>
</html>